In [2]:
import numpy as np
import pandas as pd
from IPython.display import HTML
from pandarallel import pandarallel
pandarallel.initialize()

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.


In [3]:
path_shared = '~/Downloads/nfl-big-data-bowl-2021/{}'

games_df = pd.read_csv(path_shared.format('games.csv'))
plays_df = pd.read_csv(path_shared.format('plays.csv'))
pbp_2018 = pd.read_csv("/Users/Rishav/Downloads/play_by_play_2018.csv")
pbp_joined = pd.merge(plays_df,pbp_2018,how = "left",left_on = ["gameId", "playId"] ,right_on = ["old_game_id", "play_id"])



pbp_joined["retractable"] = np.where(((pbp_joined['roof'] == "open ") | (pbp_joined['roof'] == "closed")), 1, 0)

pbp_joined["dome"] = np.where((pbp_joined['roof'] == "dome"), 1, 0)
pbp_joined["outdoors"] = np.where((pbp_joined['roof'] == "outdoors"), 1, 0)
pbp_joined["era0"] = 0
pbp_joined["era1"] = 0
pbp_joined["era2"] = 0
pbp_joined["era3"] = 0
pbp_joined["era4"] = 1
pbp_joined["down1"] = np.where((pbp_joined['down_x'] == 1),1,0)
pbp_joined["down2"] = np.where((pbp_joined['down_x'] == 2),1,0)
pbp_joined["down3"] = np.where((pbp_joined['down_x'] == 3),1,0) 
pbp_joined["down4"] = np.where((pbp_joined['down_x'] == 4),1,0)
pbp_joined["home"] = np.where((pbp_joined['posteam'] == pbp_joined['home_team']),1,0)


players_df = pd.read_csv(path_shared.format('players.csv'))
track_df = pd.read_csv(path_shared.format('week1_norm.csv'))

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (172,173,174,175,184,185,188,189,194,195,196,197,209,210,211,232,233,237,238,239,244,246,247,277) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [12]:
params = lambda: None # create an empty object to add params
params.a_max = 6
params.s_max = 9
params.reax_t = params.s_max/params.a_max
params.avg_ball_speed = 20
params.tti_sigma = 0.45
params.cell_length = 1
vars(params)


{'a_max': 6,
 's_max': 9,
 'reax_t': 1.5,
 'avg_ball_speed': 20,
 'tti_sigma': 0.45,
 'cell_length': 1}

In [10]:
#game_id = 2018122314
#play_id = 4239
game_id = 2018090905
play_id = 2062
# game_id, play_id = random.choice(plays)

play_df = track_df[(track_df.playId == play_id) & (track_df.gameId == game_id)].sort_values(by = 'frameId')
play_df.head()

gameId  playId  frameId event      nflId          displayName  \
317421  2018090905    2062        1  None   496735.0       Kareem Jackson   
317434  2018090905    2062        1  None        0.0             Football   
317433  2018090905    2062        1  None  2558094.0      Zach Cunningham   
317432  2018090905    2062        1  None  2552490.0  Benardrick McKinney   
317430  2018090905    2062        1  None  2552261.0        Kevin Johnson   

        jerseyNumber position position_general      team team_pos teamAbbr  \
317421          25.0       CB               DB      away      DEF      HOU   
317434           NaN      NaN              NaN  football     FTBL     FTBL   
317433          41.0      ILB               LB      away      DEF      HOU   
317432          55.0      ILB               LB      away      DEF      HOU   
317430          30.0       CB               DB      away      DEF      HOU   

       route                      time    los      x      y   dis       o  \
317421   NaN  2018-09-09T18:28:11.700Z  50.91  65.42  31.08  0.08  260.44   
317434   NaN  2018-09-09T18:28:11.700Z  50.91  51.09  29.52  0.00     NaN   
317433   NaN  2018-09-09T18:28:11.700Z  50.91  55.27  32.36  0.05  263.88   
317432   NaN  2018-09-09T18:28:11.700Z  50.91  52.79  23.53  0.10  220.61   
317430   NaN  2018-09-09T18:28:11.700Z  50.91  59.31  17.56  0.05  135.60   

           s   s_dir  s_dir_rad   v_x   v_y  v_theta  v_mag  a_old  a_x  a_y  \
317421  0.83  108.40       1.89  0.79 -0.26    -0.32   0.83   0.38  0.0  0.0   
317434  0.00     NaN        NaN  0.00  0.00     0.00   0.00   0.00  0.0  0.0   
317433  0.49  262.25       4.58 -0.49 -0.07     0.14   0.49   0.72  0.0  0.0   
317432  0.95  298.75       5.21 -0.83  0.46    -0.50   0.95   0.03  0.0  0.0   
317430  0.50   27.09       0.47  0.23  0.45     1.10   0.50   0.46  0.0  0.0   

        a_theta  a_mag  
317421      0.0    0.0  
317434      0.0    0.0  
317433      0.0    0.0  
317432      0.0    0.0  
317430      0.0    0.0

In [5]:
import xgboost as xgb
import joblib
import treelite_runtime
bst = joblib.load("xyac_model.model")
xgb.plot_importance(bst)
scores = bst.get_score(importance_type='gain')
print(scores.keys())
cols_when_model_builds = bst.feature_names
xyac_predictor = treelite_runtime.Predictor('./xyacmymodel.dylib', verbose=True)
print("ADDED NEW SHIT")


epa_model = joblib.load("epa_model_rishav_no_time.model")
xgb.plot_importance(epa_model)
scores = epa_model.get_score(importance_type='gain')
cols_when_model_builds_ep = epa_model.feature_names
epa_predictor = treelite_runtime.Predictor('./epa_no_time_mymodel.dylib', verbose=True)

print("ADDED MEME")

dict_keys(['1-closest-defender-distance', '1-closest-defender-x', '1-closest-defender-y', 'y', '5-closest-defender-distance', '5-closest-defender-speed', '2-closest-defender-distance', '2-closest-defender-speed', '4-closest-defender-x', '2-closest-defender-y', '1-closest-defender-speed', '2-closest-defender-x', '3-closest-defender-distance', '4-closest-defender-speed', '5-closest-defender-x', '3-closest-defender-speed', '3-closest-defender-x', '4-closest-defender-y', '3-closest-defender-y', '4-closest-defender-distance', '5-closest-defender-y'])
[01:38:44] /usr/local/lib/python3.7/site-packages/treelite_runtime/predictor.py:309: Dynamic shared library /Users/Rishav/Documents/2021bdbwinners/BigDataBowl/analysis/xyacmymodel.dylib has been successfully loaded into memory
ADDED NEW SHIT
[01:38:47] /usr/local/lib/python3.7/site-packages/treelite_runtime/predictor.py:309: Dynamic shared library /Users/Rishav/Documents/2021bdbwinners/BigDataBowl/analysis/epa_no_time_mymodel.dylib has been suc

In [8]:
#### WE WILL CALCULATE THE EP MATRIX HERE TO MAKE THINGS EZ

### GET ENDPOINTS

x = np.linspace(0.5, 119.5, 120)
epvals = np.array([7,-7,3,-3,2,-2,0])
joined_df = pbp_joined[(pbp_joined.playId == play_id) & (pbp_joined.gameId == game_id)]

    
epa_df = pd.DataFrame({
        'play_endpoint_x': x,
     })

test = {}
for feat in epa_model.feature_names:
    test[feat] = [joined_df.iloc[0][feat]]
    epa_df[feat] = joined_df.iloc[0][feat]

first_df = pd.DataFrame(test)

dtest = treelite_runtime.Batch.from_npy2d(first_df[cols_when_model_builds_ep].values)
ypred = epa_predictor.predict(dtest)
ep = np.sum(ypred*epvals, axis = 1)
print(ep)
print("YAY")
epa_df["before_play_ep"] = ep[0]
    
    
    
epa_df['los'] = 100 - epa_df['yardline_100']
epa_df['first_down_line'] = epa_df['los'] + epa_df["ydstogo"] #fix this
epa_df['expected_end_up_line'] = epa_df['play_endpoint_x']

epa_df['isFirstDown'] = 0
epa_df['isFirstDown'] = np.where(epa_df['expected_end_up_line'] >= epa_df['first_down_line'], 1, 0)

epa_df['yardline_100'] = np.round(110 - epa_df['expected_end_up_line'])
epa_df['yardline_100'] = np.where(epa_df['yardline_100'] > 100, 100 , epa_df['yardline_100'])
epa_df['ydstogo'] = epa_df['first_down_line'] - epa_df['expected_end_up_line']
epa_df['ydstogo'] = np.where(epa_df['isFirstDown'] == 1, 10, epa_df['ydstogo'])
downthing = joined_df.iloc[0]['down_x']
print(downthing)
for d in range(1,4):
    epa_df['down%d' % d] = 1 if (d == downthing+1) else 0
    
epa_df['down1'] = np.where(epa_df['isFirstDown'] == 1, 1, epa_df['down1'])
epa_df['down2'] = np.where(epa_df['isFirstDown'] == 1, 0, epa_df['down2'])
epa_df['down3'] = np.where(epa_df['isFirstDown'] == 1, 0, epa_df['down3'])
epa_df['down4'] = np.where(epa_df['isFirstDown'] == 1, 0, epa_df['down4'])

### UPDATE EPA VARIABLES

dtest = treelite_runtime.Batch.from_npy2d(epa_df[cols_when_model_builds_ep].values)
ypred = epa_predictor.predict(dtest)
ep = np.sum(ypred*epvals, axis = 1)
epa_df['xep'] = ep
### SCORE SAFETIES
epa_df['xep'] = np.where(epa_df['play_endpoint_x'] < 10, -2, epa_df['xep'])
### SCORE Tds 
epa_df['xep'] = np.where(epa_df['play_endpoint_x'] > 110, 7, epa_df['xep'])

epa_df['xepa'] = epa_df['xep'] - epa_df['before_play_ep']

only_vals = epa_df[["play_endpoint_x", "xep", "xepa"]]

display(epa_df[epa_df.play_endpoint_x == 68.5])

### CALCULATE OUTPUT

[1.7271648]
YAY
1


play_endpoint_x  yardline_100  home  retractable  dome  outdoors  ydstogo  \
68             68.5          42.0     1            0     0         1     10.0   

    era0  era1  era2  era3  era4  down1  down2  down3  down4  \
68     0     0     0     0     1      1      0      0      0   

    posteam_timeouts_remaining  defteam_timeouts_remaining  before_play_ep  \
68                         1.0                         3.0        1.727165   

     los  first_down_line  expected_end_up_line  isFirstDown       xep  \
68  41.0             51.0                  68.5            1  2.556347   

        xepa  
68  0.829182

In [ ]:
%%time
import time
from scipy.spatial import distance
from ipdb import launch_ipdb_on_exception 

def get_field_df(play_frame_group):
    time1 = time.time()
    frame_df = play_frame_group.loc[(play_df.nflId!=0)]
    ball_start = frame_df.loc[frame_df.position=='QB', ['x', 'y']].iloc[0].round(0)
    frame_df = frame_df.loc[frame_df.position!='QB']
    #print(frame_df.columns)
    current_frame = min(frame_df.frameId)
    pocket_width = 10

    x = np.linspace(0.5, 119.5, 120)
    y = np.linspace(-0.5, 53.5, 55)
    y[0] = -0.2
    field_locs = np.stack(np.meshgrid(x, y)).reshape(2, -1).T  # (F, 2)
    
    T = np.linspace(0.1, 4, 40)
    receivers_df = frame_df.loc[frame_df.team_pos == 'DEF',['x', 'y', 'v_x', 'v_y', 'v_theta', 'v_mag', 'los', 'a_x', 'a_y']]
    dist_from_ball_np = np.linalg.norm((receivers_df.x - ball_start[0],
                                                     receivers_df.y - ball_start[1]), axis=0)
    # find the spot the qb would aim at, leading the receiver in their current dir by the ball time
    rec_x_np = receivers_df.x.to_numpy()[:,None]
    rec_y_np = receivers_df.y.to_numpy()[:,None]
    rec_v_x_np = receivers_df.v_x.to_numpy()[:,None]
    rec_v_y_np = receivers_df.v_y.to_numpy()[:,None]
    rec_a_x_np = receivers_df.a_x.to_numpy()[:,None]
    rec_a_y_np = receivers_df.a_y.to_numpy()[:,None]
    rec_v_theta_np = receivers_df.v_theta.to_numpy()[:,None]
    rec_v_x_r = rec_a_x_np*params.reax_t+rec_v_x_np
    rec_v_y_r = rec_a_y_np*params.reax_t+rec_v_y_np
    rec_v_r_mag = np.linalg.norm(np.array([rec_v_x_r, rec_v_y_r]), axis=0)
    rec_v_r_theta = np.arctan(rec_v_y_r/rec_v_x_r)
    
    #target_x = rec_x_np+rec_v_x_np*t+0.5*rec_a_x_np*t**2  # (R, T)
    #target_y = rec_y_np+rec_v_y_np*t+0.5*rec_a_y_np*t**2  # (R, T)
    
    x_r = rec_x_np + rec_v_x_np*params.reax_t + 0.5*rec_a_x_np*params.reax_t**2 #(R, 1)
    y_r = rec_y_np + rec_v_y_np*params.reax_t + 0.5*rec_a_y_np*params.reax_t**2 #(R, 1)
    
    reaction_player_locs = np.hstack((x_r, y_r)) # (R,2)
    reaction_player_vels = np.hstack((rec_v_x_r, rec_v_y_r)) # (R,2)
    
    int_d_vec = field_locs[:, None, :] - reaction_player_locs #(F, R, 2)
    int_d_mag = np.linalg.norm(int_d_vec, axis=2) # F, R
    int_theta = np.arctan(int_d_vec[:,:,1]/int_d_vec[:,:,0]) #this could be a problem
    
    
    int_s0 = np.clip(np.sum(int_d_vec*reaction_player_vels, axis=2)/int_d_mag, -params.s_max, params.s_max) #F, R,  #taking norm between vectors int_d and player velocity
        
    t_lt_smax = (params.s_max-int_s0)/params.a_max  #F, J,
    d_lt_smax = t_lt_smax*((int_s0+params.s_max)/2) #F, J,
    d_at_smax = int_d_mag - d_lt_smax               #F, J,
    t_at_smax = d_at_smax/params.s_max              #F, J,
    t_tot = t_lt_smax+t_at_smax                     #F, J,
    
    cap = np.broadcast_to(t_tot[:,:,None],(*t_lt_smax.shape, len(T)))
    a1 =  np.broadcast_to(t_lt_smax[:,:,None],(*t_lt_smax.shape, len(T))) # F, J, T THIS IS TIME SPENT LT SMAX
    a2 =  np.broadcast_to(t_tot[:,:,None],(*t_lt_smax.shape, len(T))) # F, J, T
    
    time_lt_smax = np.where(a1 > a2, a2, a1) # F, J, T  THIS IS TIME LESS THAN MAX
    time_at_smax = a2 - time_lt_smax # F, J, T THIS IS TIME MORE at max
    
    
    
    d = time_at_smax * params.s_max + int_s0[:,:,None]*time_lt_smax + 0.5*params.a_max*np.square(time_lt_smax) # F, J, T
    # d should be at most the magnitude
    
    #print(d)
    #print(int_s0)
    ## d = Time at max speed * max speed + int_s0* time at lt_smax + 1/2 params.a_max (time at lt_smax * time at lt_smax) 
    #d = 
    v_proj = int_s0[:,:,None] + params.a_max*time_lt_smax # F, J, T
    v_proj = np.where(v_proj > params.s_max, params.s_max, v_proj) # F, J, T
    v_proj = np.abs(v_proj)
    x_proj = x_r + d* np.cos(int_theta[:,:,None]) # F, J, T
    y_proj = y_r + d* np.sin(int_theta[:,:,None]) # F, J, T
    
    x_proj_relv = x_proj -  field_locs[:,None,None,0] # F, J, T #GET RELATIVE COORDS
    y_proj_relv = y_proj -  field_locs[:,None,None,1] # F, J, T #GET RELATIVE COORDS
    
    
    projected_locations = np.stack((x_proj, y_proj), axis =3)  # F, J, T, 2
    
    distances_to_ball = projected_locations - field_locs[:,None,None,:] # F, J, T, 2
    distance_mags = np.linalg.norm(distances_to_ball, axis = 3) # F, J, T

    sorted_indices = np.argsort(distance_mags, axis = 1) # F, J, T

    distance_mags = np.take_along_axis(distance_mags,sorted_indices, axis = 1)
    x_proj_sorted = np.take_along_axis(x_proj_relv,sorted_indices, axis = 1) # F, J, T
    y_proj_sorted = np.take_along_axis(y_proj_relv,sorted_indices, axis = 1) # F, J, T
    v_proj_sorted = np.take_along_axis(v_proj,sorted_indices, axis = 1) # F, J, T
    
    just_top_5_distances = distance_mags[:,0:5,:].transpose((0,2,1)) #F, T, 5
    just_top_5_x_proj = x_proj_sorted[:,0:5,:].transpose((0,2,1)) #F, T, 5
    just_top_5_y_proj = y_proj_sorted[:,0:5,:].transpose((0,2,1))  #F, T, 5
    just_top_5_v_proj = v_proj_sorted[:,0:5,:].transpose((0,2,1))  #F, T, 5
    
    
    just_top_5_distances = np.reshape(just_top_5_distances, (just_top_5_distances.shape[0]*just_top_5_distances.shape[1],just_top_5_distances.shape[2]))
    just_top_5_x_proj  = np.reshape(just_top_5_x_proj, just_top_5_distances.shape)
    just_top_5_y_proj  = np.reshape(just_top_5_y_proj, just_top_5_distances.shape)
    just_top_5_v_proj  = np.reshape(just_top_5_v_proj, just_top_5_distances.shape)

    
    endpoints = np.repeat(field_locs, repeats = len(T), axis = 0) # FxT, 2
    times = np.repeat(T[None, :], repeats = len(field_locs), axis = 0)
    times_shaped = times.reshape((times.shape[0]*times.shape[1]))# FxT, 1
    value_array = np.array([-2.5,2.5,7.5,12.5,17.5, 22.5, 27.5, 30])
    
    
    field_df = pd.DataFrame({
        'pass_endpoint_x': endpoints[:,0],
        'pass_endpoint_y': endpoints[:,1],
        'frame_thrown' : current_frame,
        'time_of_flight' : times_shaped,
        '1-closest-defender-distance' : just_top_5_distances[:,0],
        '2-closest-defender-distance' : just_top_5_distances[:,1],
        '3-closest-defender-distance' : just_top_5_distances[:,2],
        '4-closest-defender-distance' : just_top_5_distances[:,3],
        '5-closest-defender-distance' : just_top_5_distances[:,4],
        '1-closest-defender-x' : just_top_5_x_proj[:,0],
        '2-closest-defender-x' : just_top_5_x_proj[:,1],
        '3-closest-defender-x' : just_top_5_x_proj[:,2],
        '4-closest-defender-x' : just_top_5_x_proj[:,3],
        '5-closest-defender-x' : just_top_5_x_proj[:,4],
        '1-closest-defender-y' : just_top_5_y_proj[:,0], 
        '2-closest-defender-y': just_top_5_y_proj[:,1], 
        '3-closest-defender-y': just_top_5_y_proj[:,2], 
        '4-closest-defender-y': just_top_5_y_proj[:,3], 
        '5-closest-defender-y': just_top_5_y_proj[:,4], 
        '1-closest-defender-speed' : just_top_5_v_proj[:,0],
        '2-closest-defender-speed': just_top_5_v_proj[:,1],
        '3-closest-defender-speed': just_top_5_v_proj[:,2],
        '4-closest-defender-speed': just_top_5_v_proj[:,3],
        '5-closest-defender-speed': just_top_5_v_proj[:,4], 
        "y" : endpoints[:,1]
        
     })
    ### CALCULTE XYAC
    
    
    dtest = treelite_runtime.Batch.from_npy2d(field_df[cols_when_model_builds].values)
    ypred = xyac_predictor.predict(dtest)
    y_vals = np.sum(ypred*value_array, axis = 1)
    field_df['xyac'] = y_vals
    field_df['play_endpoint_x'] = np.round(field_df['xyac'] + field_df['pass_endpoint_x'])
    field_df['play_endpoint_x'] = field_df['play_endpoint_x']+.5
    field_df['play_endpoint_x'] = np.where(field_df['play_endpoint_x'] > 120, 119.5, field_df['play_endpoint_x'])
    
    
    time2 = time.time()
    print(time2-time1)
    #print(2/0)
    return field_df


field_dfs = play_df.loc[play_df.frameId <= play_df.loc[play_df.event=='pass_forward'].frameId.iloc[0]].groupby(['gameId', 'playId', 'frameId']).apply(get_field_df)
field_dfs = field_dfs.reset_index(3, drop=True).reset_index()

field_dfs

3.175610065460205
4.289465665817261
3.72436785697937
6.236963987350464
3.26647686958313
3.164299964904785
3.1905100345611572
3.0573549270629883
3.1695961952209473
3.138360023498535
3.344464063644409
3.293031930923462
3.071286678314209


In [14]:
added_epa = field_dfs.merge(only_vals)
added_epa

gameId  playId  frameId  pass_endpoint_x  pass_endpoint_y  \
0         2018090905    2062        1              0.5             -0.2   
1         2018090905    2062        1              0.5             -0.2   
2         2018090905    2062        1              0.5             -0.2   
3         2018090905    2062        1              0.5             -0.2   
4         2018090905    2062        1              0.5             -0.2   
5         2018090905    2062        1              0.5             -0.2   
6         2018090905    2062        1              0.5             -0.2   
7         2018090905    2062        1              0.5             -0.2   
8         2018090905    2062        1              0.5             -0.2   
9         2018090905    2062        1              0.5             -0.2   
10        2018090905    2062        1              0.5             -0.2   
11        2018090905    2062        1              0.5             -0.2   
12        2018090905    2062        1              0.5             -0.2   
13        2018090905    2062        1              0.5             -0.2   
14        2018090905    2062        1              0.5             -0.2   
15        2018090905    2062        1              0.5             -0.2   
16        2018090905    2062        1              0.5             -0.2   
17        2018090905    2062        1              0.5             -0.2   
18        2018090905    2062        1              0.5             -0.2   
19        2018090905    2062        1              0.5             -0.2   
20        2018090905    2062        1              0.5             -0.2   
21        2018090905    2062        1              0.5             -0.2   
22        2018090905    2062        1              0.5             -0.2   
23        2018090905    2062        1              0.5             -0.2   
24        2018090905    2062        1              0.5             -0.2   
25        2018090905    2062        1              0.5             -0.2   
26        2018090905    2062        1              0.5             -0.2   
27        2018090905    2062        1              0.5             -0.2   
28        2018090905    2062        1              0.5             -0.2   
29        2018090905    2062        1              0.5             -0.2   
30        2018090905    2062        1              0.5             -0.2   
31        2018090905    2062        1              0.5             -0.2   
32        2018090905    2062        1              0.5             -0.2   
33        2018090905    2062        1              0.5             -0.2   
34        2018090905    2062        1              0.5             -0.2   
35        2018090905    2062        1              0.5             -0.2   
36        2018090905    2062        1              0.5             -0.2   
37        2018090905    2062        1              0.5             -0.2   
38        2018090905    2062        1              0.5             -0.2   
39        2018090905    2062        1              0.5             -0.2   
40        2018090905    2062        1              0.5              0.5   
41        2018090905    2062        1              0.5              0.5   
42        2018090905    2062        1              0.5              0.5   
43        2018090905    2062        1              0.5              0.5   
44        2018090905    2062        1              0.5              0.5   
45        2018090905    2062        1              0.5              0.5   
46        2018090905    2062        1              0.5              0.5   
47        2018090905    2062        1              0.5              0.5   
48        2018090905    2062        1              0.5              0.5   
49        2018090905    2062        1              0.5              0.5   
...              ...     ...      ...              ...              ...   
12143950  2018090905    2062       44              0.5             50.5   
12143951  2018090905    2062       44  

In [21]:
expanded = pd.read_csv("plays_with_passer_expanded_with_z_norm.csv")
expanded_stuff = expanded[(expanded.playId == play_id) & (expanded.gameId == game_id)]
endpointx, endpointy = 73.5, 16.5

print(expanded_stuff)
endpointx,endpointy = round(endpointx)+.5, round(endpointy)+.5

possible_passes = added_epa[(added_epa.pass_endpoint_x == endpointx) & (added_epa.pass_endpoint_y == endpointy) 
                            & (added_epa.frameId ==  46)   ]
possible_passes.sort_values('time_of_flight')[['pass_endpoint_x','pass_endpoint_y', "1-closest-defender-distance", "time_of_flight","play_endpoint_x", "xyac", "xep", "xepa"]]


     Unnamed: 0    X   X1      gameId  playId  \
407         408  408  439  2018090905    2062   

                                       playDescription  quarter  down  \
407  (1:05) (Shotgun) T.Brady pass deep middle to R...        2     1   

     yardsToGo possessionTeam        playType yardlineSide  yardlineNumber  \
407         10             NE  play_type_pass           NE              41   

    offenseFormation        personnelO  defendersInTheBox  \
407          SHOTGUN  2 RB, 1 TE, 2 WR                6.0   

     numberOfPassRushers        personnelD typeDropback  preSnapVisitorScore  \
407                    4  4 DL, 2 LB, 5 DB  TRADITIONAL                  6.0   

     preSnapHomeScore gameClock  absoluteYardlineNumber penaltyCodes  \
407              14.0  01:05:00                    69.0          NaN   

    penaltyJerseyNumbers passResult  offensePlayResult  playResult       epa  \
407                  NaN          C                 28          28  1.248695   

     is

pass_endpoint_x  pass_endpoint_y  1-closest-defender-distance  \
7404992             74.5             16.5                     7.053906   
7404993             74.5             16.5                     5.931186   
7120420             74.5             16.5                     4.858466   
7025019             74.5             16.5                     3.835746   
6834224             74.5             16.5                     2.863026   
6929517             74.5             16.5                     1.940305   
6738544             74.5             16.5                     1.067585   
6738545             74.5             16.5                     0.244865   
6929518             74.5             16.5                     0.527855   
6929519             74.5             16.5                     1.250575   
6929520             74.5             16.5                     1.081669   
6929521             74.5             16.5                     0.675395   
6738546             74.5             16.5                     0.319120   
6738547             74.5             16.5                     0.012846   
6452320             74.5             16.5                     0.243428   
6452321             74.5             16.5                     0.449702   
6738548             74.5             16.5                     0.605977   
6929522             74.5             16.5                     0.712251   
6929523             74.5             16.5                     0.768525   
6834225             74.5             16.5                     0.774799   
6929524             74.5             16.5                     0.731074   
6738549             74.5             16.5                     0.637348   
6738550             74.5             16.5                     0.493622   
6929525             74.5             16.5                     0.299896   
6452322             74.5             16.5                     0.056171   
6549101             74.5             16.5                     0.237555   
6643889             74.5             16.5                     0.581281   
6643890             74.5             16.5                     0.975007   
6643891             74.5             16.5                     1.418732   
6643892             74.5             16.5                     1.912458   
6738551             74.5             16.5                     2.456184   
7309920             74.5             16.5                     3.049910   
7309921             74.5             16.5                     3.693635   
7309922             74.5             16.5                     3.595859   
7404994             74.5             16.5                     3.068579   
7594361             74.5             16.5                     2.491299   
7404995             74.5             16.5                     1.864019   
7309923             74.5             16.5                     1.186739   
7215034             74.5             16.5                     0.459459   
7309924             74.5             16.5                     0.317821   

         time_of_flight  play_endpoint_x      xyac       xep      xepa  
7404992             0.1             83.5  8.219148  3.724057  1.996892  
7404993             0.2             83.5  8.080729  3.724057  1.996892  
7120420             0.3             80.5  5.592665  3.333764  1.606599  
7025019             0.4             79.5  4.620849  3.333764  1.606599  
6834224             0.5             78.5  3.692853  3.234888  1.507723  
6929517             0.6             77.5  2.939466  3.234888  1.507723  
6738544             0.7             76.5  1.285268  3.071147  1.343982  
6738545             0.8             76.5  1.484129  3.071147  1.343982  
6929518             0.9             77.5  2.111656  3.234888  1.507723  
6929519             1.0             77.5  2.393685  3.234888  1.507723  
6929520             1.1             77.5  2.276794  3.234888  1.507723  
6929521             1.2             77.5  2.404860  3.234888  1.507723  
6738546             1.3  

In [14]:
#HERE WE WILL GET PLAY INFORMATION FROM NFLFASTR JOINED


test_df = field_dfs[:1000]

joined_df = pbp_joined[(pbp_joined.playId == play_id) & (pbp_joined.gameId == game_id)]
epvals = np.array([7,-7,3,-3,2,-2,0])
print(joined_df.iloc[0]["ep"], joined_df.iloc[0]["epa_y"], )




for feat in epa_model.feature_names:
    test_df[feat] = joined_df.iloc[0][feat]
    

dtest = xgb.DMatrix(test_df[cols_when_model_builds][:1])
print("wtf is going on 1")
ypred = epa_model.predict(dtest)
print("wtf is going on 2")
ep = np.sum(ypred*epvals, axis = 1)

print("wtf is going on")
test_df["rish_ep"] = ep[0]
display(test_df)

0.7214394946349785 3.3343231148901395


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


wtf is going on 1
wtf is going on 2
wtf is going on


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


gameId  playId  frameId  pass_endpoint_x  pass_endpoint_y  \
0    2018090905    2062        1              0.5             -0.2   
1    2018090905    2062        1              0.5             -0.2   
2    2018090905    2062        1              0.5             -0.2   
3    2018090905    2062        1              0.5             -0.2   
4    2018090905    2062        1              0.5             -0.2   
5    2018090905    2062        1              0.5             -0.2   
6    2018090905    2062        1              0.5             -0.2   
7    2018090905    2062        1              0.5             -0.2   
8    2018090905    2062        1              0.5             -0.2   
9    2018090905    2062        1              0.5             -0.2   
10   2018090905    2062        1              0.5             -0.2   
11   2018090905    2062        1              0.5             -0.2   
12   2018090905    2062        1              0.5             -0.2   
13   2018090905    2062        1              0.5             -0.2   
14   2018090905    2062        1              0.5             -0.2   
15   2018090905    2062        1              0.5             -0.2   
16   2018090905    2062        1              0.5             -0.2   
17   2018090905    2062        1              0.5             -0.2   
18   2018090905    2062        1              0.5             -0.2   
19   2018090905    2062        1              0.5             -0.2   
20   2018090905    2062        1              0.5             -0.2   
21   2018090905    2062        1              0.5             -0.2   
22   2018090905    2062        1              0.5             -0.2   
23   2018090905    2062        1              0.5             -0.2   
24   2018090905    2062        1              0.5             -0.2   
25   2018090905    2062        1              0.5             -0.2   
26   2018090905    2062        1              0.5             -0.2   
27   2018090905    2062        1              0.5             -0.2   
28   2018090905    2062        1              0.5             -0.2   
29   2018090905    2062        1              0.5             -0.2   
30   2018090905    2062        1              0.5             -0.2   
31   2018090905    2062        1              0.5             -0.2   
32   2018090905    2062        1              0.5             -0.2   
33   2018090905    2062        1              0.5             -0.2   
34   2018090905    2062        1              0.5             -0.2   
35   2018090905    2062        1              0.5             -0.2   
36   2018090905    2062        1              0.5             -0.2   
37   2018090905    2062        1              0.5             -0.2   
38   2018090905    2062        1              0.5             -0.2   
39   2018090905    2062        1              0.5             -0.2   
40   2018090905    2062        1              1.5             -0.2   
41   2018090905    2062        1              1.5             -0.2   
42   2018090905    2062        1              1.5             -0.2   
43   2018090905    2062        1              1.5             -0.2   
44   2018090905    2062        1              1.5             -0.2   
45   2018090905    2062        1              1.5             -0.2   
46   2018090905    2062        1              1.5             -0.2   
47   2018090905    2062        1              1.5             -0.2   
48   2018090905    2062        1              1.5             -0.2   
49   2018090905    2062        1              1.5             -0.2   
..          ...     ...      ...              ...              ...   
950  2018090905    2062        1             23.5             -0.2   
951  2018090905    2062        1             23.5             -0.2   
952  2018090905    2062        1             23.5             -0.2   
953  2018090905    2062        1             23.5             -0.2   
954  2018090905    2062        1             23.5             -0.2   
955  2018090905    

In [ ]:
from visualize import AnimatePlay
animated_play = AnimatePlay(play_df, 20)
HTML(animated_play.ani.to_jshtml())

In [ ]:
import time
import traceback, sys, code

g = play_df.groupby(['gameId', 'playId', 'frameId'])
for name, group in list(g)[45:46]:
    start = time.time()
    print(f'{name} started')
    try: 
        get_field_df(group)
    except:
        type, value, tb = sys.exc_info()
        traceback.print_exc()
        last_frame = lambda tb=tb: last_frame(tb.tb_next) if tb.tb_next else tb
        frame = last_frame().tb_frame
        ns = dict(frame.f_globals)
        ns.update(frame.f_locals)
        code.interact(local=ns)
        # breakpoint()
    print(f'{name} ended {time.time()-start} ')
    

    


(2018090905, 2062, 46) started


Traceback (most recent call last):
  File "<ipython-input-15-c8d143ef2d10>", line 9, in <module>
    get_field_df(group)
  File "<timed exec>", line 157, in get_field_df
ZeroDivisionError: division by zero
Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)


3.287648916244507
In : reaction_player_locs[120*36.5 + 47.5]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In : reaction_player_locs[(120*36 + 47)]


IndexError: index 4367 is out of bounds for axis 0 with size 7

In : reaction_player_locs[120*36.5 + 47.5]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In : reaction_player_locs


array([[41.75867347, 47.91969388],
       [60.21357143, 16.68438776],
       [61.61377551,  2.23714286],
       [60.55469388, 13.06846939],
       [46.9405102 ,  9.4127551 ],
       [65.11612245, 49.29091837],
       [70.94193878, 29.49846939]])

In : l 120*36 + 47


SyntaxError: invalid syntax (<console>, line 1)

In : l = 120*36 + 47
In : field_locs[l]


array([47.5, 35.5])

In : l = 120*36 + 46
In : l


4366

In : l = 120*36 + 48
In : field_locs[l
...: ]


array([48.5, 35.5])

In : l = 120*37 + 46
In : field_locs[l]


array([46.5, 36.5])

In : l = 120*37 + 47
In : field_locs[l]


array([47.5, 36.5])

In : projected_locations[l]


array([[[ 4.13806482e+01,  4.86715989e+01],
        [ 4.10340658e+01,  4.93609632e+01],
        [ 4.07189262e+01,  4.99877866e+01],
        [ 4.04352294e+01,  5.05520693e+01],
        [ 4.01829753e+01,  5.10538111e+01],
        [ 3.99621641e+01,  5.14930122e+01],
        [ 3.97727956e+01,  5.18696725e+01],
        [ 3.96148700e+01,  5.21837920e+01],
        [ 3.94883871e+01,  5.24353707e+01],
        [ 3.93933471e+01,  5.26244086e+01],
        [ 3.93297498e+01,  5.27509057e+01],
        [ 3.92975953e+01,  5.28148621e+01],
        [ 3.92968836e+01,  5.28162776e+01],
        [ 3.93276148e+01,  5.27551524e+01],
        [ 3.93897887e+01,  5.26314863e+01],
        [ 3.94834054e+01,  5.24452795e+01],
        [ 3.96084649e+01,  5.21965319e+01],
        [ 3.97649672e+01,  5.18852434e+01],
        [ 3.99529123e+01,  5.15114142e+01],
        [ 4.01723002e+01,  5.10750442e+01],
        [ 4.04231309e+01,  5.05761334e+01],
        [ 4.07054044e+01,  5.00146819e+01],
        [ 4.10191207e+01,  4.939

In : projected_locations[l,:,15]


array([[39.48340541, 52.44527949],
       [61.71943313, 14.3373233 ],
       [61.47824901,  2.56614945],
       [60.80749345, 12.614726  ],
       [46.8742913 ,  6.20682046],
       [63.59334239, 48.18524058],
       [73.2846279 , 28.79876576]])

In : reaction_player_locs[l]


IndexError: index 4487 is out of bounds for axis 0 with size 7

In : projected_locations[l,:,15]


array([[39.48340541, 52.44527949],
       [61.71943313, 14.3373233 ],
       [61.47824901,  2.56614945],
       [60.80749345, 12.614726  ],
       [46.8742913 ,  6.20682046],
       [63.59334239, 48.18524058],
       [73.2846279 , 28.79876576]])

In : reaction_player_locs


array([[41.75867347, 47.91969388],
       [60.21357143, 16.68438776],
       [61.61377551,  2.23714286],
       [60.55469388, 13.06846939],
       [46.9405102 ,  9.4127551 ],
       [65.11612245, 49.29091837],
       [70.94193878, 29.49846939]])

In : field_locs[l]


array([47.5, 36.5])

In : l = 120*17 + 77
In : l = 120*17 + 73
In : field_locs[l]


array([73.5, 16.5])

In : projected_locations[l,:,15]


array([[38.60761678, 51.03882113],
       [74.59813481, 16.48476019],
       [68.55144338, 10.56198696],
       [74.41757375, 16.74322966],
       [55.70539312, 11.75161297],
       [66.44525983, 44.09241267],
       [73.47344937, 16.63491371]])

In : player_locs[l]


NameError: name 'player_locs' is not defined

In : frame_df[['x','y']]


x      y
318063  45.04  39.94
318062  51.22  17.78
318061  55.89  45.81
318060  55.03   7.74
318059  41.46  17.66
318058  51.18  15.92
318057  44.55  18.14
318056  42.30  39.38
318055  50.86   5.56
318053  58.39  45.24
318052  51.72  16.97
318051  66.79  31.54

In : frame_df[['x','y', 'displayName']]


x      y          displayName
318063  45.04  39.94      Zach Cunningham
318062  51.22  17.78  Benardrick McKinney
318061  55.89  45.81      Phillip Dorsett
318060  55.03   7.74        Kevin Johnson
318059  41.46  17.66          James White
318058  51.18  15.92         Aaron Colvin
318057  44.55  18.14       Tyrann Mathieu
318056  42.30  39.38         Rex Burkhead
318055  50.86   5.56          Chris Hogan
318053  58.39  45.24     Johnathan Joseph
318052  51.72  16.97       Rob Gronkowski
318051  66.79  31.54       Kareem Jackson

In : play_df


gameId  playId  frameId                event      nflId  \
317421  2018090905    2062        1                 None   496735.0   
317434  2018090905    2062        1                 None        0.0   
317433  2018090905    2062        1                 None  2558094.0   
317432  2018090905    2062        1                 None  2552490.0   
317430  2018090905    2062        1                 None  2552261.0   
317429  2018090905    2062        1                 None  2543773.0   
317428  2018090905    2062        1                 None  2543501.0   
317431  2018090905    2062        1                 None  2552424.0   
317426  2018090905    2062        1                 None  2539265.0   
317425  2018090905    2062        1                 None  2530515.0   
317424  2018090905    2062        1                 None  2504211.0   
317423  2018090905    2062        1                 None  2495872.0   
317422  2018090905    2062        1                 None   497240.0   
317427  2018090905    2062        1                 None  2540180.0   
317443  2018090905    2062        2                 None  2543773.0   
317448  2018090905    2062        2                 None        0.0   
317447  2018090905    2062        2                 None  2558094.0   
317446  2018090905    2062        2                 None  2552490.0   
317445  2018090905    2062        2                 None  2552424.0   
317444  2018090905    2062        2                 None  2552261.0   
317442  2018090905    2062        2                 None  2543501.0   
317438  2018090905    2062        2                 None  2504211.0   
317440  2018090905    2062        2                 None  2539265.0   
317439  2018090905    2062        2                 None  2530515.0   
317437  2018090905    2062        2                 None  2495872.0   
317436  2018090905    2062        2                 None   497240.0   
317435  2018090905    2062        2                 None   496735.0   
317441  2018090905    2062        2                 None  2540180.0   
317457  2018090905    2062        3                 None  2543773.0   
317462  2018090905    2062        3                 None        0.0   
317461  2018090905    2062        3                 None  2558094.0   
317460  2018090905    2062        3                 None  2552490.0   
317459  2018090905    2062        3                 None  2552424.0   
317458  2018090905    2062        3                 None  2552261.0   
317456  2018090905    2062        3                 None  2543501.0   
317452  2018090905    2062        3                 None  2504211.0   
317454  2018090905    2062        3                 None  2539265.0   
317453  2018090905    2062        3                 None  2530515.0   
317451  2018090905    2062        3                 None  2495872.0   
317450  2018090905    2062        3                 None   497240.0   
317449  2018090905    2062        3                 None   496735.0   
317455  2018090905    2062        3                 None  2540180.0   
317476  2018090905    2062        4                 None        0.0   
317475  2018090905    2062        4                 None  2558094.0   
317474  2018090905    2062        4                 None  2552490.0   
317473  2018090905    2062        4                 None  2552424.0   
317472  2018090905    2062        4                 None  2552261.0   
317471  2018090905    2062        4                 None  2543773.0   
317470  2018090905    2062        4                 None  2543501.0   
317468  2018090905    2062        4                 None  2539265.0   
...            ...     ...      ...                  ...        ...   
318338  2018090905    2062       66                 None  2543501.0   
318337  2018090905    2062       66                 None  2540180.0   
318336  2018090905    2062       66                 None  2539265.0   
318335  2018090905    2062       66                 None  2530515.0   
318334  2018090905    2062       66 

In : play_df[play_df.frameId == 62]


gameId  playId  frameId         event      nflId  \
318288  2018090905    2062       62  pass_arrived        0.0   
318287  2018090905    2062       62  pass_arrived  2558094.0   
318286  2018090905    2062       62  pass_arrived  2552490.0   
318285  2018090905    2062       62  pass_arrived  2552424.0   
318284  2018090905    2062       62  pass_arrived  2552261.0   
318283  2018090905    2062       62  pass_arrived  2543773.0   
318282  2018090905    2062       62  pass_arrived  2543501.0   
318280  2018090905    2062       62  pass_arrived  2539265.0   
318279  2018090905    2062       62  pass_arrived  2530515.0   
318278  2018090905    2062       62  pass_arrived  2504211.0   
318277  2018090905    2062       62  pass_arrived  2495872.0   
318276  2018090905    2062       62  pass_arrived   497240.0   
318275  2018090905    2062       62  pass_arrived   496735.0   
318281  2018090905    2062       62  pass_arrived  2540180.0   

                displayName  jerseyNumber position      team team_pos  \
318288             Football           NaN      NaN  football     FTBL   
318287      Zach Cunningham          41.0      ILB      away      DEF   
318286  Benardrick McKinney          55.0      ILB      away      DEF   
318285      Phillip Dorsett          13.0       WR      home      OFF   
318284        Kevin Johnson          30.0       CB      away      DEF   
318283          James White          28.0       RB      home      OFF   
318282         Aaron Colvin          22.0       CB      away      DEF   
318280         Rex Burkhead          34.0       RB      home      OFF   
318279          Chris Hogan          15.0       WR      home      OFF   
318278            Tom Brady          12.0       QB      home      OFF   
318277     Johnathan Joseph          24.0       CB      away      DEF   
318276       Rob Gronkowski          87.0       TE      home      OFF   
318275       Kareem Jackson          25.0       CB      away      DEF   
318281       Tyrann Mathieu          32.0       FS      away      DEF   

       teamAbbr route                      time  los      x      y   dis  \
318288     FTBL   NaN  2018-09-09T18:28:17.799Z   40  62.00  17.33  2.30   
318287      HOU   NaN  2018-09-09T18:28:17.799Z   40  44.50  47.28  0.33   
318286      HOU   NaN  2018-09-09T18:28:17.799Z   40  61.91  16.20  0.70   
318285       NE    GO  2018-09-09T18:28:17.799Z   40  66.59  50.80  0.54   
318284      HOU   NaN  2018-09-09T18:28:17.799Z   40  61.84   2.39  0.50   
318283       NE   OUT  2018-09-09T18:28:17.799Z   40  42.37  10.37  0.25   
318282      HOU   NaN  2018-09-09T18:28:17.799Z   40  62.89  15.52  0.80   
318280       NE   OUT  2018-09-09T18:28:17.799Z   40  43.29  47.60  0.33   
318279       NE    GO  2018-09-09T18:28:17.799Z   40  61.26   2.70  0.54   
318278       NE   NaN  2018-09-09T18:28:17.799Z   40  31.24  30.96  0.12   
318277      HOU   NaN  2018-09-09T18:28:17.799Z   40  67.18  49.83  0.54   
318276       NE    GO  2018-09-09T18:28:17.799Z   40  62.71  16.36  0.79   
318275      HOU   NaN  2018-09-09T18:28:17.799Z   40  70.23  25.47  0.67   
318281      HOU   NaN  2018-09-09T18:28:17.799Z   40  50.14  11.00  0.55   

             o      s   s_dir  s_dir_rad    v_x   v_y  v_theta  v_mag  a_old  \
318288     NaN  20.65     NaN        NaN  21.30 -8.80    -0.39  23.05   6.66   
318287  182.05   3.32   28.61       0.50   1.59  2.91     1.07   3.32   3.35   
318286   95.01   6.96   93.20       1.63   6.95 -0.39    -0.06   6.96   0.99   
318285   78.35   5.21   66.38       1.16   4.77  2.09     0.41   5.21   3.69   
318284  349.40   4.88  101.78       1.78   4.78 -1.00    -0.21   4.88   2.60   
318283  123.20   2.37  168.11       2.93   0.49 -2.32    -1.36   2.37   2.69   
318282   52.55   7.95   75.69       1.32   7.70  1.96     0.25   7.95   1.40   
318280   79.66   3.18   17.15       0.30   0.94  3.04     1.27   3.18   3.11   
318279   57.04   5.24   89.54       1.56   5.24  0.04     0.01   5.24   3.21   
318278   80.23

In : b = play_df[play_df.frameId == 62]
In : b[['x', 'y', "displayName"]]


x      y          displayName
318288  62.00  17.33             Football
318287  44.50  47.28      Zach Cunningham
318286  61.91  16.20  Benardrick McKinney
318285  66.59  50.80      Phillip Dorsett
318284  61.84   2.39        Kevin Johnson
318283  42.37  10.37          James White
318282  62.89  15.52         Aaron Colvin
318280  43.29  47.60         Rex Burkhead
318279  61.26   2.70          Chris Hogan
318278  31.24  30.96            Tom Brady
318277  67.18  49.83     Johnathan Joseph
318276  62.71  16.36       Rob Gronkowski
318275  70.23  25.47       Kareem Jackson
318281  50.14  11.00       Tyrann Mathieu

In : projected_locs[l, :, 15]


NameError: name 'projected_locs' is not defined

In : projected_locations[l,:,15]


array([[38.60761678, 51.03882113],
       [74.59813481, 16.48476019],
       [68.55144338, 10.56198696],
       [74.41757375, 16.74322966],
       [55.70539312, 11.75161297],
       [66.44525983, 44.09241267],
       [73.47344937, 16.63491371]])

In : b[['x', 'y', "displayName"]]


x      y          displayName
318288  62.00  17.33             Football
318287  44.50  47.28      Zach Cunningham
318286  61.91  16.20  Benardrick McKinney
318285  66.59  50.80      Phillip Dorsett
318284  61.84   2.39        Kevin Johnson
318283  42.37  10.37          James White
318282  62.89  15.52         Aaron Colvin
318280  43.29  47.60         Rex Burkhead
318279  61.26   2.70          Chris Hogan
318278  31.24  30.96            Tom Brady
318277  67.18  49.83     Johnathan Joseph
318276  62.71  16.36       Rob Gronkowski
318275  70.23  25.47       Kareem Jackson
318281  50.14  11.00       Tyrann Mathieu

In : b.loc[['x', 'y', "displayName", 'team_pos']]


KeyError: "None of [Index(['x', 'y', 'displayName', 'team_pos'], dtype='object')] are in the [index]"

In : b[['x', 'y', "displayName", 'team_pos']]


x      y          displayName team_pos
318288  62.00  17.33             Football     FTBL
318287  44.50  47.28      Zach Cunningham      DEF
318286  61.91  16.20  Benardrick McKinney      DEF
318285  66.59  50.80      Phillip Dorsett      OFF
318284  61.84   2.39        Kevin Johnson      DEF
318283  42.37  10.37          James White      OFF
318282  62.89  15.52         Aaron Colvin      DEF
318280  43.29  47.60         Rex Burkhead      OFF
318279  61.26   2.70          Chris Hogan      OFF
318278  31.24  30.96            Tom Brady      OFF
318277  67.18  49.83     Johnathan Joseph      DEF
318276  62.71  16.36       Rob Gronkowski      OFF
318275  70.23  25.47       Kareem Jackson      DEF
318281  50.14  11.00       Tyrann Mathieu      DEF

In : b.loc[b.team_pos == "DEF",['x', 'y', "displayName", 'team_pos']]


x      y          displayName team_pos
318287  44.50  47.28      Zach Cunningham      DEF
318286  61.91  16.20  Benardrick McKinney      DEF
318284  61.84   2.39        Kevin Johnson      DEF
318282  62.89  15.52         Aaron Colvin      DEF
318277  67.18  49.83     Johnathan Joseph      DEF
318275  70.23  25.47       Kareem Jackson      DEF
318281  50.14  11.00       Tyrann Mathieu      DEF

In : projected_locations[l,:,15]


array([[38.60761678, 51.03882113],
       [74.59813481, 16.48476019],
       [68.55144338, 10.56198696],
       [74.41757375, 16.74322966],
       [55.70539312, 11.75161297],
       [66.44525983, 44.09241267],
       [73.47344937, 16.63491371]])


KeyboardInterrupt


In : quit()
In : q


NameError: name 'q' is not defined

In : exit()
In : pls


NameError: name 'pls' is not defined

In : quit


In : quit()
In : 
In : 
In : 



KeyboardInterrupt
